### ISSUE TITLE
feat: add Swap Factory Contract

### ISSUE THREAD

**Issue by dpinones** [blockful-io/swaplace-cairo#3]
Implement the [Swap Factory Contract](https://github.com/blockful-io/swaplace-contracts/blob/main/contracts/SwapFactory.sol).

**Comment by 0xneves** [comment]
I reviewed the code and doesn't make much sense to have this feature in Cairo.
It's very easy to create structs and there are no issues on creating them on-chain compared to Solidity.
I'm closing this issue as resolved.
